# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

#### 1)  crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na tempreatura global, A NASA disponibiliza dados de diferenças de de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo.

|ano|anomalia termica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.

In [1]:
import pandas as pd
import numpy as np

# Seu código aqui
ano = [1900, 1920, 1940, 1960, 1980, 2000, 2020]
serie_ano = pd.Series(data=ano)
print(serie_ano)
anomalia = [-0.08, -0.27, 0.12, -0.03, 0.26, 0.40, 1.02]
serie_anomalia = pd.Series(data=anomalia)
print(serie_anomalia)

0    1900
1    1920
2    1940
3    1960
4    1980
5    2000
6    2020
dtype: int64
0   -0.08
1   -0.27
2    0.12
3   -0.03
4    0.26
5    0.40
6    1.02
dtype: float64

#### 2) Coloque os anos nos índices conforme a tabela.

In [2]:
# seu código aqui
serie_temperatura = pd.Series(data=anomalia, index=ano)
serie_temperatura

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64

#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:

In [3]:
dic_temperaturas = {1900: -.08, 1920: -.27, 1940: .12, 1960: -.03, 1980: .26, 2000: .40, 2020: 1.02}

# seu código aqui
serie_temperaturas = pd.Series(dic_temperaturas)
serie_temperaturas

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64

#### 4) Transforme o ndarray abaixo em um dataframe.
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.

In [4]:
arr = np.random.normal(100, 10, (20,3))

# seu código aqui
dfarr = pd.DataFrame(arr)
dfarr

             0           1           2
0    94.560931  101.913647  106.740204
1   101.091860  105.308679   98.469254
2    99.111543   99.004067   91.450318
3    94.363598  107.593514  110.690512
4    98.078824  104.841643   88.346684
5    91.012843  111.857107  108.142868
6   115.541979   90.125576  108.090106
7    88.531129   93.660989   94.624181
8   105.480857  117.425172   94.006793
9   102.990199  115.411439  119.178810
10  121.862570   92.552760   99.093759
11   92.822705  107.575255   92.789356
12  101.510537   95.653570  115.662452
13  105.810961  106.566880   84.304219
14   89.629913   95.690890   85.591066
15  100.949796   83.463294  105.649645
16  107.916224  117.297503  104.522033
17   97.612247  109.922201  104.368129
18   94.680099  100.816881   79.496066
19  126.533143   88.805618   98.955315

#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente.

In [5]:
#seu código aqui
indices = range(1,21)
nomes_colunas = ["x1", "x2", "x3"]
dfarrcomindice = pd.DataFrame(data = arr, index = indices, columns = nomes_colunas)
dfarrcomindice

            x1          x2          x3
1    94.560931  101.913647  106.740204
2   101.091860  105.308679   98.469254
3    99.111543   99.004067   91.450318
4    94.363598  107.593514  110.690512
5    98.078824  104.841643   88.346684
6    91.012843  111.857107  108.142868
7   115.541979   90.125576  108.090106
8    88.531129   93.660989   94.624181
9   105.480857  117.425172   94.006793
10  102.990199  115.411439  119.178810
11  121.862570   92.552760   99.093759
12   92.822705  107.575255   92.789356
13  101.510537   95.653570  115.662452
14  105.810961  106.566880   84.304219
15   89.629913   95.690890   85.591066
16  100.949796   83.463294  105.649645
17  107.916224  117.297503  104.522033
18   97.612247  109.922201  104.368129
19   94.680099  100.816881   79.496066
20  126.533143   88.805618   98.955315

#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis).

In [6]:
# seu código aqui
dfarrcomindice['media'] = dfarrcomindice.mean(axis=1)
dfarrcomindice

            x1          x2          x3       media
1    94.560931  101.913647  106.740204  101.071594
2   101.091860  105.308679   98.469254  101.623265
3    99.111543   99.004067   91.450318   96.521976
4    94.363598  107.593514  110.690512  104.215875
5    98.078824  104.841643   88.346684   97.089050
6    91.012843  111.857107  108.142868  103.670939
7   115.541979   90.125576  108.090106  104.585887
8    88.531129   93.660989   94.624181   92.272100
9   105.480857  117.425172   94.006793  105.637607
10  102.990199  115.411439  119.178810  112.526816
11  121.862570   92.552760   99.093759  104.503029
12   92.822705  107.575255   92.789356   97.729105
13  101.510537   95.653570  115.662452  104.275520
14  105.810961  106.566880   84.304219   98.894020
15   89.629913   95.690890   85.591066   90.303956
16  100.949796   83.463294  105.649645   96.687578
17  107.916224  117.297503  104.522033  109.911920
18   97.612247  109.922201  104.368129  103.967526
19   94.680099  100.816881   79.496066   91.664349
20  126.533143   88.805618   98.955315  104.764692

#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>

In [7]:
# seu código aqui
dfarrcomindice['log_med'] = np.log(dfarrcomindice['media'])
dfarrcomindice

            x1          x2          x3       media   log_med
1    94.560931  101.913647  106.740204  101.071594  4.615829
2   101.091860  105.308679   98.469254  101.623265  4.621272
3    99.111543   99.004067   91.450318   96.521976  4.569771
4    94.363598  107.593514  110.690512  104.215875  4.646464
5    98.078824  104.841643   88.346684   97.089050  4.575629
6    91.012843  111.857107  108.142868  103.670939  4.641222
7   115.541979   90.125576  108.090106  104.585887  4.650009
8    88.531129   93.660989   94.624181   92.272100  4.524742
9   105.480857  117.425172   94.006793  105.637607  4.660014
10  102.990199  115.411439  119.178810  112.526816  4.723192
11  121.862570   92.552760   99.093759  104.503029  4.649216
12   92.822705  107.575255   92.789356   97.729105  4.582199
13  101.510537   95.653570  115.662452  104.275520  4.647037
14  105.810961  106.566880   84.304219   98.894020  4.594049
15   89.629913   95.690890   85.591066   90.303956  4.503181
16  100.949796   83.463294  105.649645   96.687578  4.571485
17  107.916224  117.297503  104.522033  109.911920  4.699679
18   97.612247  109.922201  104.368129  103.967526  4.644079
19   94.680099  100.816881   79.496066   91.664349  4.518134
20  126.533143   88.805618   98.955315  104.764692  4.651717